#!/usr/bin/env node
// fetch-fonts.mjs : self-host the fonts so the site stops calling Google Fonts.
// One-time build tool, run by hand, not part of publish.sh.
//
// WHY
// Every page load was a round trip to fonts.googleapis.com for a CSS file that
// then pulled woff2 files from fonts.gstatic.com. That is a third-party
// dependency in the critical path, a privacy leak on a site whose footer claims
// "no cookies, no trackers", and two more hosts the CSP has to allow forever.
//
// WHAT IT DOES
// Reads the Google Fonts CSS with a modern browser UA (that is what gets woff2
// rather than ttf), downloads each unicode-range latin subset into fonts/, and
// writes fonts.css with @font-face rules and local file paths. Then it rewrites
// colors_and_type.css to drop the @import and every page drops its preconnect.
//
//   node scripts/fetch-fonts.mjs
//
// Six files: three families, latin and latin-ext subsets. Inter and Fraunces are
// variable fonts, so each ships one file per subset with a weight range rather
// than one file per weight, which would be 300 KB of identical bytes.
// No em dashes.

import { mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const FONT_DIR = join(root, 'fonts');
mkdirSync(FONT_DIR, { recursive: true });

// Exactly what the design system declares in system.css.
const FAMILIES = [
  { css: 'Inter:wght@400;500;600;700', local: 'Inter', file: 'inter' },
  { css: 'JetBrains+Mono:wght@400;600', local: 'JetBrains Mono', file: 'jetbrains-mono' },
  // Fraunces is a variable optical-size serif. The site uses 700 and 800 only.
  { css: 'Fraunces:opsz,wght@9..144,700;9..144,800', local: 'Fraunces', file: 'fraunces' },
];

const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const GOOGLE = 'https://fonts.googleapis.com/css2';

async function get(url, asBuffer = false) {
  const res = await fetch(url, { headers: { 'user-agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return asBuffer ? Buffer.from(await res.arrayBuffer()) : res.text();
}

// Parse the Google CSS into faces, keeping only the latin block. The parser is
// deliberately small: it reads @font-face blocks and the /* latin */ comment
// that Google puts above each one.
function parseFaces(css) {
  const faces = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/gi;
  let m;
  while ((m = re.exec(css))) {
    const subset = m[1].toLowerCase();
    if (subset !== 'latin' && subset !== 'latin-ext') continue;
    const body = m[2];
    const pick = (k) => {
      const r = new RegExp(`${k}:\\s*([^;]+);`, 'i');
      const v = body.match(r);
      return v ? v[1].trim() : null;
    };
    const weight = pick('font-weight') || '400';
    const style = pick('font-style') || 'normal';
    const url = (body.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
    const range = pick('unicode-range');
    if (!url) continue;
    faces.push({ subset, weight, style, url, range });
  }
  return faces;
}

const out = [
  '/* fonts.css : self-hosted. Generated by scripts/fetch-fonts.mjs, do not edit by hand.',
  '   Three families, latin and latin-ext subsets only, woff2, variable where the',
  '   family is variable. This site makes no request to fonts.googleapis.com or',
  '   fonts.gstatic.com any more. */',
  '',
];

let count = 0;
let bytes = 0;

for (const fam of FAMILIES) {
  // The query goes into the URL exactly as written. Google wants a literal "+"
  // in "JetBrains+Mono" and literal ";" and "," as weight separators; encoding
  // any of them (encodeURIComponent, or %2B, or %3B) returns a 400. Verified
  // against the live API: the raw form is 200, the encoded form is 400.
  const css = await get(`${GOOGLE}?family=${fam.css}&display=swap`);
  const faces = parseFaces(css);
  if (!faces.length) throw new Error(`no latin face found for ${fam.local}`);

  // Inter and Fraunces are variable fonts, so Google returns the same file for
// every weight asked for. Dedupe by content hash and emit one @font-face per
// subset with a weight range, otherwise 300 KB of identical woff2 ships.
const byContent = new Map();
for (const f of faces) {
  if (!byContent.has(f.url)) byContent.set(f.url, { url: f.url, subset: f.subset, range: f.range, weights: new Set(), style: f.style });
  byContent.get(f.url).weights.add(f.weight);
}

for (const f of byContent.values()) {
  const name = `${fam.file}-${f.subset}.woff2`;
  const dest = join(FONT_DIR, name);
  if (!existsSync(dest)) {
    const buf = await get(f.url, true);
    writeFileSync(dest, buf);
    count++;
    bytes += buf.length;
  }
  const ws = [...f.weights].sort();
  const weight = ws.length > 1 ? `${ws[0]} ${ws[ws.length - 1]}` : ws[0];
  out.push(
    '@font-face {',
    `  font-family: '${fam.local}';`,
    `  font-style: ${f.style};`,
    `  font-weight: ${weight};`,
    '  font-display: swap;',
    `  src: url('fonts/${name}') format('woff2');`,
    ...(f.range ? [`  unicode-range: ${f.range};`] : []),
    '}',
    ''
  );
}

} // end for (const fam of FAMILIES)

writeFileSync(join(root, 'fonts.css'), out.join('\n'), 'utf8');

// Drop the @import from the legacy sheet. It is the only place the site still
// reached out to Google.
const legacyPath = join(root, 'colors_and_type.css');
if (existsSync(legacyPath)) {
  let legacy = readFileSync(legacyPath, 'utf8');
  const before = legacy.length;
  legacy = legacy.replace(/@import\s+url\(['"]?https:\/\/fonts\.googleapis\.com[^)]*\);?\s*/g, '');
  if (!/fonts\.css/.test(legacy)) {
    // @import must be the first rule in the file to be valid CSS.
    legacy = `@import url('fonts.css');\n${legacy}`;
  }
  writeFileSync(legacyPath, legacy, 'utf8');
  console.log(`colors_and_type.css: removed ${before - legacy.length} bytes of google fonts import, points at fonts.css now`);
}

// Every page that preconnected to Google needs those lines gone.
const pages = readdirSync(root).filter((f) => f.endsWith('.html'));
let touched = 0;
for (const p of pages) {
  const path = join(root, p);
  let src = readFileSync(path, 'utf8');
  const orig = src;
  src = src
    .replace(/[ \t]*<link rel="preconnect" href="https:\/\/fonts\.(googleapis|gstatic)\.com"[^>]*>\n?/g, '')
    .replace(/[ \t]*<link rel="stylesheet" href="https:\/\/fonts\.googleapis\.com[^"]*"[^>]*>\n?/g, '')
    // Make sure the local sheet is loaded, ahead of the legacy sheets.
    .replace(/(<link rel="stylesheet" href="colors_and_type\.css">)/, '$1\n  <link rel="stylesheet" href="fonts.css">');
  if (src !== orig) { writeFileSync(path, src, 'utf8'); touched++; }
}

console.log(`fetched ${count} font files (${(bytes / 1024).toFixed(0)} KB), ${touched} pages rewired to fonts.css`);
console.log('verify with: grep -r "fonts.googleapis" *.html *.css   (should be empty)');
